mysql:
  image: mysql:5.7
  ports:
  - "3307:3306"
  expose:
  - "3307"
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=
  volumes:
  - "./conf.d:/docker-entrypoint-initdb.d/"

mysql-test:
  image: mysql:5.7
  ports:
  - "3308:3306"
  expose:
  - "3308"
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=
  volumes:
  - "./test-conf.d:/docker-entrypoint-initdb.d/"
